## Supervised Learning

### Case Study- 2 (CS 31)
---

### Objectives:

**Learn to handle missing values.<br>
Learn to fit a decision tree and compare its accuracy with random forest classifier.**

### Importing libraries and loading data

In [32]:
import pandas as pd
import matplotlib.pyplot as plot
import numpy as np

In [33]:
# Loading the given data

df = pd.read_csv("datasets/horse.csv")
df

,surgery,age,hospital_number,rectal_temp,pulse,respiratory_rate,temp_of_extremities,peripheral_pulse,mucous_membrane,capillary_refill_time,...,packed_cell_volume,total_protein,abdomo_appearance,abdomo_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
0,no,adult,530101,38.5,66.0,28.0,cool,reduced,NaN,more_3_sec,...,45.0,8.4,NaN,NaN,died,no,11300,0,0,no
1,yes,adult,534817,39.2,88.0,20.0,NaN,NaN,pale_cyanotic,less_3_sec,...,50.0,85.0,cloudy,2.0,euthanized,no,2208,0,0,no
2,no,adult,530334,38.3,40.0,24.0,normal,normal,pale_pink,less_3_sec,...,33.0,6.7,NaN,NaN,lived,no,0,0,0,yes
3,yes,young,5290409,39.1,164.0,84.0,cold,normal,dark_cyanotic,more_3_sec,...,48.0,7.2,serosanguious,5.3,died,yes,2208,0,0,yes
4,no,adult,530255,37.3,104.0,35.0,NaN,NaN,dark_cyanotic,more_3_sec,...,74.0,7.4,NaN,NaN,died,no,4300,0,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,yes,adult,533886,NaN,120.0,70.0,cold,NaN,pale_cyanotic,more_3_sec,...,55.0,65.0,NaN,NaN,euthanized,no,3205,0,0,no
295,no,adult,527702,37.2,72.0,24.0,cool,increased,pale_cyanotic,more_3_sec,...,44.0,NaN,serosanguious,3.3,euthanized,yes,2208,0,0,yes
296,yes,adult,529386,37.5,72.0,30.0,cold,reduced,pale_cyanotic,less_3_sec,...,60.0,6.8,NaN,NaN,died,yes,3205,0,0,no
297,yes,adult,530612,36.5,100.0,24.0,cool,reduced,pale_pink,less_3_sec,...,50.0,6.0,serosanguious,3.4,lived,yes,2208,0,0,yes
298,yes,adult,534618,37.2,40.0,20.0,NaN,NaN,NaN,NaN,...,36.0,62.0,clear,1.0,euthanized,no,6112,0,0,no

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   surgery                299 non-null    object
 1   age                    299 non-null    object
 2   hospital_number        299 non-null    int64
 3   rectal_temp            239 non-null    float64
 4   pulse                  275 non-null    float64
 5   respiratory_rate       241 non-null    float64
 6   temp_of_extremities    243 non-null    object
 7   peripheral_pulse       230 non-null    object
 8   mucous_membrane        252 non-null    object
 9   capillary_refill_time  267 non-null    object
 10  pain                   244 non-null    object
 11  peristalsis            255 non-null    object
 12  abdominal_distention   243 non-null    object
 13  nasogastric_tube       195 non-null    object
 14  nasogastric_reflux     193 non-null    object
 15  nasogastric_reflux_ph  53 non-null     float64
 16  rectal_exam_feces      197 non-null    object
 17  abdomen                181 non-null    object
 18  packed_cell_volume     270 non-null    float64
 19  total_protein          266 non-null    float64
 20  abdomo_appearance      134 non-null    object
 21  abdomo_protein         101 non-null    float64
 22  outcome                299 non-null    object
 23  surgical_lesion        299 non-null    object
 24  lesion_1               299 non-null    int64
 25  lesion_2               299 non-null    int64
 26  lesion_3               299 non-null    int64
 27  cp_data                299 non-null    object
dtypes: float64(7), int64(4), object(17)
memory usage: 65.5+ KB

In [35]:
df.describe()

,hospital_number,rectal_temp,pulse,respiratory_rate,nasogastric_reflux_ph,packed_cell_volume,total_protein,abdomo_protein,lesion_1,lesion_2,lesion_3
count,2.990000e+02,239.000000,275.000000,241.000000,53.000000,270.000000,266.000000,101.000000,299.000000,299.000000,299.000000
mean,1.087733e+06,38.168619,72.000000,30.460581,4.707547,46.307407,24.274436,3.039604,3659.709030,90.528428,7.387960
std,1.532032e+06,0.733744,28.646219,17.666102,1.982311,10.436743,27.364194,1.967947,5408.472421,650.637139,127.749768
min,5.184760e+05,35.400000,30.000000,8.000000,1.000000,23.000000,3.300000,0.100000,0.000000,0.000000,0.000000
25%,5.289040e+05,37.800000,48.000000,18.000000,3.000000,38.000000,6.500000,2.000000,2111.500000,0.000000,0.000000
50%,5.303010e+05,38.200000,64.000000,25.000000,5.000000,45.000000,7.500000,2.300000,2322.000000,0.000000,0.000000
75%,5.347360e+05,38.500000,88.000000,36.000000,6.500000,52.000000,56.750000,3.900000,3209.000000,0.000000,0.000000
max,5.305629e+06,40.800000,184.000000,96.000000,7.500000,75.000000,89.000000,10.100000,41110.000000,7111.000000,2209.000000

In [36]:
df.isnull().sum()

surgery                    0
age                        0
hospital_number            0
rectal_temp               60
pulse                     24
respiratory_rate          58
temp_of_extremities       56
peripheral_pulse          69
mucous_membrane           47
capillary_refill_time     32
pain                      55
peristalsis               44
abdominal_distention      56
nasogastric_tube         104
nasogastric_reflux       106
nasogastric_reflux_ph    246
rectal_exam_feces        102
abdomen                  118
packed_cell_volume        29
total_protein             33
abdomo_appearance        165
abdomo_protein           198
outcome                    0
surgical_lesion            0
lesion_1                   0
lesion_2                   0
lesion_3                   0
cp_data                    0
dtype: int64

In [37]:
df.dtypes

surgery                   object
age                       object
hospital_number            int64
rectal_temp              float64
pulse                    float64
respiratory_rate         float64
temp_of_extremities       object
peripheral_pulse          object
mucous_membrane           object
capillary_refill_time     object
pain                      object
peristalsis               object
abdominal_distention      object
nasogastric_tube          object
nasogastric_reflux        object
nasogastric_reflux_ph    float64
rectal_exam_feces         object
abdomen                   object
packed_cell_volume       float64
total_protein            float64
abdomo_appearance         object
abdomo_protein           float64
outcome                   object
surgical_lesion           object
lesion_1                   int64
lesion_2                   int64
lesion_3                   int64
cp_data                   object
dtype: object

### Q1. Let’s attempt to predict the survival of a horse based on various observed medical conditions. Load the data from ‘horses.csv’ and observe whether it contains missing values. Category Column (Y- Values) -Column -outcome.

In [38]:
print(df.groupby('outcome').size())

outcome
died           77
euthanized     44
lived         178
dtype: int64

In [39]:
OC = df['outcome']
print(OC.unique())

['died' 'euthanized' 'lived']

In [40]:
df = df.drop(['outcome'], axis=1)
df

,surgery,age,hospital_number,rectal_temp,pulse,respiratory_rate,temp_of_extremities,peripheral_pulse,mucous_membrane,capillary_refill_time,...,abdomen,packed_cell_volume,total_protein,abdomo_appearance,abdomo_protein,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
0,no,adult,530101,38.5,66.0,28.0,cool,reduced,NaN,more_3_sec,...,distend_large,45.0,8.4,NaN,NaN,no,11300,0,0,no
1,yes,adult,534817,39.2,88.0,20.0,NaN,NaN,pale_cyanotic,less_3_sec,...,other,50.0,85.0,cloudy,2.0,no,2208,0,0,no
2,no,adult,530334,38.3,40.0,24.0,normal,normal,pale_pink,less_3_sec,...,normal,33.0,6.7,NaN,NaN,no,0,0,0,yes
3,yes,young,5290409,39.1,164.0,84.0,cold,normal,dark_cyanotic,more_3_sec,...,NaN,48.0,7.2,serosanguious,5.3,yes,2208,0,0,yes
4,no,adult,530255,37.3,104.0,35.0,NaN,NaN,dark_cyanotic,more_3_sec,...,NaN,74.0,7.4,NaN,NaN,no,4300,0,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,yes,adult,533886,NaN,120.0,70.0,cold,NaN,pale_cyanotic,more_3_sec,...,distend_large,55.0,65.0,NaN,NaN,no,3205,0,0,no
295,no,adult,527702,37.2,72.0,24.0,cool,increased,pale_cyanotic,more_3_sec,...,distend_small,44.0,NaN,serosanguious,3.3,yes,2208,0,0,yes
296,yes,adult,529386,37.5,72.0,30.0,cold,reduced,pale_cyanotic,less_3_sec,...,distend_large,60.0,6.8,NaN,NaN,yes,3205,0,0,no
297,yes,adult,530612,36.5,100.0,24.0,cool,reduced,pale_pink,less_3_sec,...,distend_small,50.0,6.0,serosanguious,3.4,yes,2208,0,0,yes
298,yes,adult,534618,37.2,40.0,20.0,NaN,NaN,NaN,NaN,...,normal,36.0,62.0,clear,1.0,no,6112,0,0,no

---

### Q2. Replace the missing values by the most frequent value in each column.

In [41]:
Null_Val = pd.concat([df.isnull().sum(),df.dtypes], axis = 1)
Null_Val.columns= ['Null_Count', 'Datatype']
Null_Val

                       Null_Count Datatype
surgery                         0   object
age                             0   object
hospital_number                 0    int64
rectal_temp                    60  float64
pulse                          24  float64
respiratory_rate               58  float64
temp_of_extremities            56   object
peripheral_pulse               69   object
mucous_membrane                47   object
capillary_refill_time          32   object
pain                           55   object
peristalsis                    44   object
abdominal_distention           56   object
nasogastric_tube              104   object
nasogastric_reflux            106   object
nasogastric_reflux_ph         246  float64
rectal_exam_feces             102   object
abdomen                       118   object
packed_cell_volume             29  float64
total_protein                  33  float64
abdomo_appearance             165   object
abdomo_protein                198  float64
surgical_lesion                 0   object
lesion_1                        0    int64
lesion_2                        0    int64
lesion_3                        0    int64
cp_data                         0   object

### Columns with missing values and data types

In [42]:
category_cols= Null_Val[(Null_Val.Null_Count>0)&(Null_Val.Datatype=='object')]
category_cols

                       Null_Count Datatype
temp_of_extremities            56   object
peripheral_pulse               69   object
mucous_membrane                47   object
capillary_refill_time          32   object
pain                           55   object
peristalsis                    44   object
abdominal_distention           56   object
nasogastric_tube              104   object
nasogastric_reflux            106   object
rectal_exam_feces             102   object
abdomen                       118   object
abdomo_appearance             165   object

In [43]:
category_variables = list(category_cols.index)
category_variables

['temp_of_extremities',
 'peripheral_pulse',
 'mucous_membrane',
 'capillary_refill_time',
 'pain',
 'peristalsis',
 'abdominal_distention',
 'nasogastric_tube',
 'nasogastric_reflux',
 'rectal_exam_feces',
 'abdomen',
 'abdomo_appearance']

### Update missing values

In [44]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(strategy="most_frequent")
df[category_variables]= imp.fit_transform(df[category_variables])
df

,surgery,age,hospital_number,rectal_temp,pulse,respiratory_rate,temp_of_extremities,peripheral_pulse,mucous_membrane,capillary_refill_time,...,abdomen,packed_cell_volume,total_protein,abdomo_appearance,abdomo_protein,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
0,no,adult,530101,38.5,66.0,28.0,cool,reduced,normal_pink,more_3_sec,...,distend_large,45.0,8.4,cloudy,NaN,no,11300,0,0,no
1,yes,adult,534817,39.2,88.0,20.0,cool,normal,pale_cyanotic,less_3_sec,...,other,50.0,85.0,cloudy,2.0,no,2208,0,0,no
2,no,adult,530334,38.3,40.0,24.0,normal,normal,pale_pink,less_3_sec,...,normal,33.0,6.7,cloudy,NaN,no,0,0,0,yes
3,yes,young,5290409,39.1,164.0,84.0,cold,normal,dark_cyanotic,more_3_sec,...,distend_large,48.0,7.2,serosanguious,5.3,yes,2208,0,0,yes
4,no,adult,530255,37.3,104.0,35.0,cool,normal,dark_cyanotic,more_3_sec,...,distend_large,74.0,7.4,cloudy,NaN,no,4300,0,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,yes,adult,533886,NaN,120.0,70.0,cold,normal,pale_cyanotic,more_3_sec,...,distend_large,55.0,65.0,cloudy,NaN,no,3205,0,0,no
295,no,adult,527702,37.2,72.0,24.0,cool,increased,pale_cyanotic,more_3_sec,...,distend_small,44.0,NaN,serosanguious,3.3,yes,2208,0,0,yes
296,yes,adult,529386,37.5,72.0,30.0,cold,reduced,pale_cyanotic,less_3_sec,...,distend_large,60.0,6.8,cloudy,NaN,yes,3205,0,0,no
297,yes,adult,530612,36.5,100.0,24.0,cool,reduced,pale_pink,less_3_sec,...,distend_small,50.0,6.0,serosanguious,3.4,yes,2208,0,0,yes
298,yes,adult,534618,37.2,40.0,20.0,cool,normal,normal_pink,less_3_sec,...,normal,36.0,62.0,clear,1.0,no,6112,0,0,no

### Checking missing value count

In [45]:
Null_Val = pd.concat([df.isnull().sum(),df.dtypes], axis = 1)
Null_Val.columns= ['Null_Count', 'Datatype']
Null_Val

                       Null_Count Datatype
surgery                         0   object
age                             0   object
hospital_number                 0    int64
rectal_temp                    60  float64
pulse                          24  float64
respiratory_rate               58  float64
temp_of_extremities             0   object
peripheral_pulse                0   object
mucous_membrane                 0   object
capillary_refill_time           0   object
pain                            0   object
peristalsis                     0   object
abdominal_distention            0   object
nasogastric_tube                0   object
nasogastric_reflux              0   object
nasogastric_reflux_ph         246  float64
rectal_exam_feces               0   object
abdomen                         0   object
packed_cell_volume             29  float64
total_protein                  33  float64
abdomo_appearance               0   object
abdomo_protein                198  float64
surgical_lesion                 0   object
lesion_1                        0    int64
lesion_2                        0    int64
lesion_3                        0    int64
cp_data                         0   object

### Save result

In [46]:
df.to_excel("datasets/processed/CS32.xlsx")

### Float columns with missing record count

In [47]:
float_cols= Null_Val[(Null_Val.Null_Count>0)]
float_cols

                       Null_Count Datatype
rectal_temp                    60  float64
pulse                          24  float64
respiratory_rate               58  float64
nasogastric_reflux_ph         246  float64
packed_cell_volume             29  float64
total_protein                  33  float64
abdomo_protein                198  float64

In [48]:
float_variables = list(float_cols.index)
float_variables

['rectal_temp',
 'pulse',
 'respiratory_rate',
 'nasogastric_reflux_ph',
 'packed_cell_volume',
 'total_protein',
 'abdomo_protein']

### Update missing values for float column

In [49]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(strategy="mean")
df[float_variables]= imp.fit_transform(df[float_variables])

In [50]:
df.to_excel("datasets/processed/CS32.xlsx")

In [51]:
df

,surgery,age,hospital_number,rectal_temp,pulse,respiratory_rate,temp_of_extremities,peripheral_pulse,mucous_membrane,capillary_refill_time,...,abdomen,packed_cell_volume,total_protein,abdomo_appearance,abdomo_protein,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
0,no,adult,530101,38.500000,66.0,28.0,cool,reduced,normal_pink,more_3_sec,...,distend_large,45.0,8.400000,cloudy,3.039604,no,11300,0,0,no
1,yes,adult,534817,39.200000,88.0,20.0,cool,normal,pale_cyanotic,less_3_sec,...,other,50.0,85.000000,cloudy,2.000000,no,2208,0,0,no
2,no,adult,530334,38.300000,40.0,24.0,normal,normal,pale_pink,less_3_sec,...,normal,33.0,6.700000,cloudy,3.039604,no,0,0,0,yes
3,yes,young,5290409,39.100000,164.0,84.0,cold,normal,dark_cyanotic,more_3_sec,...,distend_large,48.0,7.200000,serosanguious,5.300000,yes,2208,0,0,yes
4,no,adult,530255,37.300000,104.0,35.0,cool,normal,dark_cyanotic,more_3_sec,...,distend_large,74.0,7.400000,cloudy,3.039604,no,4300,0,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,yes,adult,533886,38.168619,120.0,70.0,cold,normal,pale_cyanotic,more_3_sec,...,distend_large,55.0,65.000000,cloudy,3.039604,no,3205,0,0,no
295,no,adult,527702,37.200000,72.0,24.0,cool,increased,pale_cyanotic,more_3_sec,...,distend_small,44.0,24.274436,serosanguious,3.300000,yes,2208,0,0,yes
296,yes,adult,529386,37.500000,72.0,30.0,cold,reduced,pale_cyanotic,less_3_sec,...,distend_large,60.0,6.800000,cloudy,3.039604,yes,3205,0,0,no
297,yes,adult,530612,36.500000,100.0,24.0,cool,reduced,pale_pink,less_3_sec,...,distend_small,50.0,6.000000,serosanguious,3.400000,yes,2208,0,0,yes
298,yes,adult,534618,37.200000,40.0,20.0,cool,normal,normal_pink,less_3_sec,...,normal,36.0,62.000000,clear,1.000000,no,6112,0,0,no

---

### Q3. Data  contains many categorical features, replace them with label encoding.

In [52]:
# Getting all columns list with data-type Object

All_cats = Null_Val[Null_Val.Datatype=='object']
All_cats = list(All_cats.index)
All_cats

['surgery',
 'age',
 'temp_of_extremities',
 'peripheral_pulse',
 'mucous_membrane',
 'capillary_refill_time',
 'pain',
 'peristalsis',
 'abdominal_distention',
 'nasogastric_tube',
 'nasogastric_reflux',
 'rectal_exam_feces',
 'abdomen',
 'abdomo_appearance',
 'surgical_lesion',
 'cp_data']

### Hot Encoding

In [53]:
new_df = df
for i in All_cats:
    new_df=pd.get_dummies(new_df, columns=[i], drop_first=True)
    
new_df.to_excel("datasets/processed/CS32_one_hot.xlsx")
new_df

,hospital_number,rectal_temp,pulse,respiratory_rate,nasogastric_reflux_ph,packed_cell_volume,total_protein,abdomo_protein,lesion_1,lesion_2,...,rectal_exam_feces_increased,rectal_exam_feces_normal,abdomen_distend_small,abdomen_firm,abdomen_normal,abdomen_other,abdomo_appearance_cloudy,abdomo_appearance_serosanguious,surgical_lesion_yes,cp_data_yes
0,530101,38.500000,66.0,28.0,4.707547,45.0,8.400000,3.039604,11300,0,...,0,0,0,0,0,0,1,0,0,0
1,534817,39.200000,88.0,20.0,4.707547,50.0,85.000000,2.000000,2208,0,...,0,0,0,0,0,1,1,0,0,0
2,530334,38.300000,40.0,24.0,4.707547,33.0,6.700000,3.039604,0,0,...,0,1,0,0,1,0,1,0,0,1
3,5290409,39.100000,164.0,84.0,5.000000,48.0,7.200000,5.300000,2208,0,...,0,0,0,0,0,0,0,1,1,1
4,530255,37.300000,104.0,35.0,4.707547,74.0,7.400000,3.039604,4300,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,533886,38.168619,120.0,70.0,4.707547,55.0,65.000000,3.039604,3205,0,...,0,0,0,0,0,0,1,0,0,0
295,527702,37.200000,72.0,24.0,4.707547,44.0,24.274436,3.300000,2208,0,...,0,0,1,0,0,0,0,1,1,1
296,529386,37.500000,72.0,30.0,4.707547,60.0,6.800000,3.039604,3205,0,...,0,0,0,0,0,0,1,0,1,0
297,530612,36.500000,100.0,24.0,4.707547,50.0,6.000000,3.400000,2208,0,...,0,0,1,0,0,0,0,1,1,1
298,534618,37.200000,40.0,20.0,4.707547,36.0,62.000000,1.000000,6112,0,...,0,0,0,0,1,0,0,0,0,0

In [54]:
OC.unique()

array(['died', 'euthanized', 'lived'], dtype=object)

### Label encoding for target column

In [55]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
target = label.fit_transform(OC)
print(target)

[0 1 2 0 0 2 2 0 1 2 2 2 2 0 2 0 0 2 2 2 2 2 2 2 2 2 2 2 0 2 0 1 2 2 2 1 1
 2 2 0 0 2 2 1 1 0 2 2 0 0 2 0 2 2 1 0 2 0 0 0 2 2 0 1 2 2 2 2 2 2 1 2 0 0
 0 1 2 2 0 2 0 2 2 0 2 2 0 1 2 2 2 0 2 0 2 2 2 1 2 2 2 1 2 2 0 2 2 2 1 0 0
 2 2 0 2 2 2 1 2 2 2 1 2 0 1 2 2 2 1 2 0 0 2 0 0 0 2 2 2 2 0 0 2 1 2 2 0 2
 2 2 0 2 2 2 2 2 1 2 2 2 0 2 1 2 1 2 2 2 1 2 0 2 0 0 2 2 0 2 1 0 2 0 2 2 2
 2 2 2 2 2 2 2 0 2 2 1 0 2 2 2 0 1 2 2 1 2 0 1 2 0 0 2 2 2 2 2 2 1 2 1 2 2
 2 2 2 0 2 1 2 2 0 2 2 2 0 2 2 1 1 0 2 0 2 2 0 2 0 2 2 1 0 0 2 2 0 1 0 2 0
 2 2 2 0 2 1 2 2 2 2 0 2 2 0 1 0 1 2 2 2 2 0 0 2 2 2 1 2 2 2 2 0 0 1 2 1 1
 0 2 1]

---

### Q4. Fit a decision tree classifier and observe the accuracy.

In [56]:
# Train-Test split

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(new_df, target, test_size=0.2, random_state=1)

print("X_train shape = {}.".format(X_train.shape))
print("X_test shape = {}.".format(X_test.shape))

X_train shape = (239, 51).
X_test shape = (60, 51).

### Decision tree model

In [57]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

DecisionTreeClassifier()

### Predictions on X_test

In [58]:
ydt_pred = dt.predict(X_test)
ydt_pred

array([1, 2, 1, 1, 0, 2, 0, 0, 2, 2, 1, 2, 2, 1, 0, 1, 0, 0, 2, 2, 0, 2,
       1, 0, 1, 2, 0, 1, 2, 1, 2, 0, 2, 0, 1, 0, 2, 2, 2, 2, 0, 2, 2, 1,
       0, 2, 1, 0, 0, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2])

### Accuracy

In [59]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(ydt_pred, y_test)
print(accuracy)

0.6166666666666667

---

### Q5. Fit a random forest classifier and observe the accuracy.

In [60]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train,y_train)

RandomForestClassifier()

### Predictions on X_test

In [61]:
yrf_pred = rf.predict(X_test)
yrf_pred

array([1, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 2, 0, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2,
       0, 2, 0, 2, 0, 2, 2, 2, 0, 0, 1, 2, 2, 2, 0, 2])

### Accuracy

In [62]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(yrf_pred, y_test)
print(acc)

0.7

---